### ISSUE TITLE
Global variables in modules are resolved incorrectly

### ISSUE THREAD

**Issue by tsnorri** [snakemake/snakemake#2499]
**Snakemake version**
7.32.4 (also 7.22.0)

**Describe the bug**
Global variables defined in a snakefile do not get resolved when the snakefile is imported as a module. Adding the variable definition to the snakefile that loads the module causes the variable to be resolved (which may not be preferable).

**Minimal example**

A.smk:
```
PYTHON = 'python'

rule all:
    shell: '{PYTHON} --version'
```

B.smk:
```
#PYTHON = "python"

module A_wf:
    snakefile: "A.smk"

use rule * from A_wf as A_*
```

Running ```snakemake -c 1 --snakefile A.smk``` produces no errors. Running ```snakemake -c 1 --snakefile B.smk A_all``` causes a ```NameError```. Uncommenting the first line causes the same command to succeed.

**Additional context**
I also tried to test by using ```pip install git+https://github.com/snakemake/snakemake``` but ```snakemake --version``` reported ```7.32.2+70.g7ffc8df8```. In any case, the bug persisted.

**Comment by Hocnonsense** [comment]
It seems that the rule is once tested no longer inside the module. 

In this case, rule all in A_wf is first wrapped as a function:
```python
def __rule_all(...):
    shell('{PYTHON} --version')
```

when shell is called, it will seach variable "PYTHON" outside the function. Unluckly, it seems that snakemake will call the function in the main workflow but not in the module.

----
After test to change "shell" to "run", I found that Once funciton from module is called, the module will be reload.

After test to assign `PYTHON = "pytho"` in `B.smk`, I found that snakemake run successfully

```log
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job stats:
job      count
-----  -------
A_all        1
total        1

Select jobs to execute...

[Tue Oct 31 15:13:09 2023]
rule A_all:
    jobid: 0
    reason: Rules with neither input nor output files are always executed.
    resources: tmpdir=/tmp

pytho --version
Python 3.10.8
[Tue Oct 31 15:13:09 2023]
Finished job 0.
1 of 1 steps (100%) done
```

It seems that when snakemake tried to dryrun, it searched the wrong workspace.

**Comment by tsnorri** [comment]
Replacing the command in A.smk with an f-string seems to resolve the issue, i.e. B.smk can be run successfully if A.smk is modified as follows:

```
PYTHON = 'python'

rule all:
    shell: f'{PYTHON} --version'
```

(Since the snakefiles that I would like to import may be maintained by someone else, I would like ordinary strings work the same way if possible.)

**Comment by SichongP** [comment]
This seems to be by design: https://snakemake.readthedocs.io/en/stable/snakefiles/modularization.html#modules

> The module is evaluated in a separate namespace, and only the selected rules are added to the current workflow. Non-rule Python statements inside the module are also evaluated in that separate namespace. They are available in the module-defining workflow under the name of the module (e.g. here other_workflow.myfunction() would call the function myfunction that has been defined in the model, e.g. in other_workflow/Snakefile).

In your case, my guess is:
1. `PYTHON` defined in A.smk is not available in B.smk namespace, snakemake fails to replace `{PYTHON}`
2. Unless `PYTHON` is defined in B.smk
3. When importing A.smk, f-string is evaluated first, replacing `f"{PYTHON}"` with variable `PYTHON` defined in A.smk

The best approach I think is to put `PYTHON` in params:

A.smk:
```
rule all:
    params: python="bash"
    shell: '{params.python} --version'
```

B.smk:
```
module A_wf:
    snakefile: "A.smk"

use rule all from A_wf as A_all with:
    params: python="python"
```

Alternatively, you can store `PYTHON` in `config` and pass that to A.smk in B.smk when importing module.

**Comment by tsnorri** [comment]
@SichongP Thank you for your reply! Adding the statement `A_wf.PYTHON = "python"` to `B.smk` did in fact make the workflow work as expected. To me it is not clear, though, why declaring the variable without the module prefix also worked; does “separate namespace” in this context mean that it still inherits all variables from the namespace of the importing snakefile?

I would still like to argue that the current approach makes the module feature quite a bit less useful than it could be. In particular, if global variables are used in a workflow, it will work when run by itself but not without redefining said variables when imported as a module. Consequently using workflows written by other authors by importing them as modules may not be worthwhile as extensive changes or boilerplate might be needed.

**Comment by SichongP** [comment]
> Adding the statement A_wf.PYTHON = "python" to B.smk did in fact make the workflow work as expected.

I actually had no idea this would work!

> To me it is not clear, though, why declaring the variable without the module prefix also worked; does “separate namespace” in this context mean that it still inherits all the variables from the namespace of the importing snakefile?

Yes, as @Hocnonsense mentioned, imported rules are wrapped as functions and called directly within namespace of the importing module (B.smk in your example). So when you define `PYTHON="python"` in B.smk, the `PYTHON` variable becomes available to the imported rules as it's in the namespace of the importing module.

> I would still like to argue that the current approach makes the module feature quite a bit less useful than it could be. In particular, if global variables are used in a workflow, it will work when run by itself but not without redefining said variables when imported as a module. Consequently using workflows written by other authors by importing them as modules may not be worthwhile as extensive changes or boilerplate may be needed.

I think the opposite is actually true -- separating namespaces of importing and imported modules is paramount because otherwise parameters, variables, config in the imported module can be silently overwritten and that is quite dangerous! Consider your example, what if A.smk needs `PYTHON=python2` but B.smk needs `PYTHON=python3`?

**Comment by Hocnonsense** [comment]
This is fixed in snakemake>9 via modulization

**Comment by Kamal-Eldin** [comment]
Hello @Hocnonsense and @tsnorri 
I'd really like to challenge the closure of this issue. I think it still persists and the suggested params solution or modules might not provide sufficient coverage for all the cases. Take this case for example:

computing an iterable to pass to an `expand` function in the `input` or `output` directives. A global variable here seems relevant, but can't be passed in`params`. So sharing this variable globally requires inclusion in every `smk` rule file that uses the same `expand` function.

Please, I hope we can look into a sustainable solution.

## suggestion
Declaring a variable in the main `Snakefile` gets passed automatically to all sub `.smk` files.

**Comment by Hocnonsense** [comment]
@Kamal-Eldin Hello, thanks for raising this up. Would you mind to provide an minimal example?

**Comment by Kamal-Eldin** [comment]
Ok @Hocnonsense. I think one use case might go as the following:

## configs
configs holds a path to a json metadata file holding file ids. These are used to compute a `LEDGER`
```
LEDGER = set(pd.read_json(config["metadata"])["id"].astype(int))
```
## rule files
suppose a `clean_text.smk` and an `segment_text.smk` rule files.
where `segment` rule uses `clean` as a module.

#### clean
```
LEDGER = set(pd.read_json(config["metadata"])["id"].astype(int))

rule clean_text:
    input:
        expand(f"path_{{grp}}.txt", grp=LEDGER)
```

#### Segment
**uses `clean` but overrides its inputs by adding an extra wildcard.**

As per my best knowledge `segment` now stills needs  another definition of`LEDGER` in its own. Now `LEDGER` has to be declared in both `smk`s.

```
LEDGER = set(pd.read_json(config["metadata"])["id"].astype(int))

module text_cleaning:
    snakefile: 'clean_text.smk'
    config: config

use rule clean_text from text_cleaning as clean_rule with:
    input: 
        expand(f"path_{{grp}}_{{lang}}.txt", grp=LEDGER, lang= config['langs'])

rule segment:
    input:
        rules.clean_rule.input
```

**Comment by Hocnonsense** [comment]
emmm you can reference ledger from module via `text_cleaning.LEDGER` after declaring it.

expand("path_{grp}_{lang}.txt", grp=text_cleaning.LEDGER, lang= config['langs'])

**Comment by Hocnonsense** [comment]
Otherwise, if you want to define variables outside, then you can use `config` directive to send it into the module. In this way, it can be more clear that where the variable from.

**Comment by Kamal-Eldin** [comment]
@Hocnonsense 
I'm on snakemake 9.6.2
If I reference `text_cleaning` as u demonstrated I get an error
`name 'text_cleaning' is not defined`
Can u please elaborate

**Comment by Hocnonsense** [comment]
emmm I guess you reference `text_cleaning` before the `module` directive, right? If not, would you mind to show me your code?

**Comment by Kamal-Eldin** [comment]
I think your suggestion @Hocnonsense is very good. It seems as far as I know, to need the access to wildcards via `lambda` as such:

```
module text_cleaning:
    snakefile: 'clean_text.smk'
    config: config
.....

expand("path_{grp}.txt", grp=lambda wildcards: text_cleaning.LEDGER)
```

**Comment by Hocnonsense** [comment]
@Kamal-Eldin weird, I expect this works:

```py
module text_cleaning:
    snakefile: 'clean_text.smk'
    config: config

expand("path_{grp}.txt", grp=text_cleaning.LEDGER)
```

**Comment by Kamal-Eldin** [comment]
No unfortunately this 
expand("path_{grp}.txt", grp=text_cleaning.LEDGER)
throws an undefined error for text_cleaning 

using text_cleaning.variable anywhere seems to fail

**Comment by Kamal-Eldin** [comment]
Is this because I limited the import from via
```
 use rule clean_text from text_cleaning as clean_rule with:
```
instead of using 
```
use rule * from text_cleaning
```

**Comment by Hocnonsense** [comment]
Oh I understand it now! 
Yes, currently module `text_cleaning` can only be registed after the first 'use rule' from it. So, In this case, `lambda wildcards: text_cleaning.LEDGER` is the only way to reference it correctly. However, if any other rule is used previously, `text_cleaning.LEDGER` can be fine

**Comment by Kamal-Eldin** [comment]
Can you please elaborate a bit by giving an example of a correct way of accessing globals via `module_name.variable` generally within another rule ? Thanks

**Comment by Hocnonsense** [comment]
For example, as shown in the tests: https://github.com/snakemake/snakemake/blob/ead894bdc35aaf0d56238dc273645b49b43622cf/tests/test_modules_all/Snakefile#L7-L26
