### ISSUE TITLE
Pathvars in module fail if used in input functions

### ISSUE THREAD

**Issue by votti** [snakemake/snakemake#3877]
**Snakemake version**
5.14.4

**Describe the bug**
If modules use `pathvars` in input functions, the pathvars somehow do not get correctly substituted. This results in a `MissingInputException`

This seems to be a special case, as otherwise input functions seem to work fine with `pathvars`.

**Minimal example**
Is implemented here:
https://github.com/FroeseLab/snakemake/tree/bug/pathvarsmodule/tests/test_pathvars_module_inputfkt

**Logs**
Of the minimal example:
```
MissingInputException in rule touch_testfile_input in file "/home/vitoz/Git/snakemake/tests/test_pathvars_module_inputfkt/module/Snakefile", line 6:
Missing input files for rule touch_testfile_input:
    output: results/testmodule/all.txt
    affected files:
        results/intermediate.txt
```
as one can see, the output has the output path correctly substituted (`<results>/all.txt` -> `results/testmodules/all.txt`) while the input file - defined via an input function - does have the wrong substitution (`<results>/intermediate.txt` -> `results/intermediate.txt` instead of `results/testmodules/intermediate.txt`)

**Comment by irm-codebase** [comment]
@votti reaching out because I faced similar issues recently.

I believe this has been fixed through this PR. If you upgrade snakemake past 9.19 you should be fine.

I *think* this PR provided the fix, for reference

https://github.com/snakemake/snakemake/pull/4105

**Comment by votti** [comment]
Hi @irm-codebase 

I updated my feature branch covering a test for this issue with the latest main, and it does look like the bug is still ocuring:
https://github.com/snakemake/snakemake/pull/3878 

```
=================================== FAILURES ===================================
________________________ test_pathvars_module_inputfkt _________________________

    def test_pathvars_module_inputfkt():
>       run(dpath("test_pathvars_module_inputfkt"))


tests/tests.py:2801: 
....
>               assert os.path.exists(targetfile), 'expected file "{}" not produced'.format(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
                    resultfile
                )
E               AssertionError: expected file "results/intermediate.txt" not produced
````

**Comment by votti** [comment]
Actually never mind - this is fixed. It was my test that had a mistake :/ 
Thanks a lot for fixing this issue!
