### ISSUE TITLE
Not understanding ChildIOException: happens both when output from the same rule or from separate rules

### ISSUE THREAD

**Issue by blaiseli** [snakemake/snakemake#390]
**Snakemake version**

I discovered this issue while working with 5.15.something. I installed 5.17.0, and the issue is still there.

**Describe the bug**

I'm not sure it's me not using snakemake correctly or an issue with snakemake, but the following behaviour doesn't make sense to me.

My workflow has a rule that creates a directory with lots of content (downloaded genomic data, for instance, let's say `test_dir`). Some other rules depend on some files among this content (gtf annotation files for instancen, let's say `test_dir/test_file`).

I get a `ChildIOException` complaining that `File/directory is a child to another output:`, mentioning the `test_dir` and `test_dir/test_file` as the culprits. This happens whether I have those two things as outputs of a single rule, or of two separate rules, where the second uses the `test_dir` as its input.

**Logs**
```
Building DAG of jobs...
ChildIOException:
File/directory is a child to another output:
/home/bli/src/10825_Cecere/Genomes/test_dir
/home/bli/src/10825_Cecere/Genomes/test_dir/test_file
```

**Minimal example**

Single rule:

```python
rule all:
    input:
        "test_dir",
        "test_dir/test_file",
        "other_file"

rule make_test_dir_and_test_file:
    output:
        directory("test_dir"),
        "test_dir/test_file"
    shell:
        """
        mkdir -p {output[0]}
        echo "test" > {output[0]}/test_file
        """

rule make_other_file:
    input:
        "test_dir/test_file"
    output:
        "other_file"
    shell:
        """
        cp {input[0]} {output[0]}
        """

```

Separate rules:

```python
rule all:
    input:
        "test_dir",
        "test_dir/test_file",
        "other_file"

rule make_test_dir_and_test_file:
    output:
        directory("test_dir")
    shell:
        """
        mkdir -p {output[0]}
        echo "test" > {output[0]}/test_file
        """

rule check_test_file:
    input:
        "test_dir"
    output:
        "test_dir/test_file"
    shell:
        """
        [ -e {output[0]} ] && touch {output[0]}
        """

rule make_other_file:
    input:
        "test_dir/test_file"
    output:
        "other_file"
    shell:
        """
        cp {input[0]} {output[0]}
        """
```

**Additional context**

I'm working on a Linux workstation using a Debian-based distribution (MX Linux) and a manually compiled Python:

```
$ uname -a
Linux pisa 4.19.0-5-amd64 #1 SMP Debian 4.19.37-2~mx17+1 (2019-05-15) x86_64 GNU/Linux
$ python --version
Python 3.8.2
$ snakemake --version
5.17.0
```

I try to run the workflow in "pretend" mode as follows:

```
$ snakemake --cores 1 -n --snakefile test.snakefile
Building DAG of jobs...
ChildIOException:
File/directory is a child to another output:
/home/bli/src/10825_Cecere/Genomes/test_dir
/home/bli/src/10825_Cecere/Genomes/test_dir/test_file
```

I saw someone recently had a similar error: https://github.com/bioinformatics-centre/BayesTyper/issues/29
Not sure whether the cause is similar.

**Comment by blaiseli** [comment]
I tried other versions of snakemake, and the error happens since at least 5.8.2, and does not happen with 5.7.4

**Comment by blaiseli** [comment]
The changes seem to have been introduced in https://github.com/snakemake/snakemake/commit/2395e5e825c221b2966ccd5a297234259f9c4219, in response to issue https://github.com/snakemake/snakemake/issues/52

**Comment by johanneskoester** [comment]
Let's see. So the reason is that no other rule should actually write to the same directory, because this would kind of contaminate it. But I think if the same rule specifies both a dir and a contained file, that should be fine. So this check is too restrictive currently. Let me have a look.

**Comment by johanneskoester** [comment]
Fixed in commit 0c289a65.

**Comment by blaiseli** [comment]
Thanks @johanneskoester 

I still have issues with `ChildIOException`. I will make a separate issue.
