### ISSUE TITLE
Group jobs in pipeline messes up file modification time

### ISSUE THREAD

**Issue by ManavalanG** [snakemake/snakemake#789]
**Snakemake version**
Tested in v5.9.1 and v5.30.0

**Describe the bug**

When snakemake’s `group:` feature is used when pipeline is run in cluster, it seemingly modifies the file modification time of all output files produced in that group. Unfortunately and not surprisingly, sometimes this results in output files being newer than its input files and therefore when rerunning the pipeline, snakemake thinks those output files need to be created again even though they shouldn't be. And this issue happens even if such output files were `protected`.

If the same pipeline is run in local mode or in cluster without the grouping feature, this problem doesn't exist.

**Minimal example**

```py
rule all:
    input:
        f"data/b.txt"

rule first:
    output:
        protected(f"data/a.txt")
    group: 'xyz'
    shell:
        r"""
        touch {output}
        """

rule second:
    input:
        f"data/a.txt"
    output:
        f"data/b.txt"
    group: 'xyz'
    shell:
        r"""
        sleep 5
        touch {output}
        """
```

**Logs**

1. When run in local mode, notice output files are at least 5 secs apart as expected.

```
# Command used: snakemake -s Snakefile
$ stat data/* | grep 'File\|Modify'
  File: ‘data/a.txt’
Modify: 2020-12-07 09:18:51.203767000 -0600
  File: ‘data/b.txt’
Modify: 2020-12-07 09:18:56.218426000 -0600
```

2. When run in cluster mode, notice output files are NOT at least 5 secs apart.

```
# Command used: snakemake --snakefile Snakefile --cluster 'sbatch' -j 4
$ stat data/* | grep 'File\|Modify'
  File: ‘data/a.txt’
Modify: 2020-12-07 09:21:03.519490744 -0600
  File: ‘data/b.txt’
Modify: 2020-12-07 09:21:03.514490722 -0600
```

3. When run in cluster mode with grouping part commented out, notice output files are again at least 5 secs apart as expected.

```
# Command used: snakemake --snakefile Snakefile --cluster 'sbatch' -j 4
$ stat data/* | grep 'File\|Modify'
  File: ‘data/a.txt’
Modify: 2020-12-07 09:36:23.160759361 -0600
  File: ‘data/b.txt’
Modify: 2020-12-07 09:37:03.208906144 -0600
```

**Additional context**
My Environment:
* SLURM 
* Red Hat

**Comment by twillis209** [comment]
I had this problem with v7.11.0. It necessitated running snakemake with `--touch` after completing the workflow. 

However, since merging in [this PR](https://github.com/snakemake/snakemake/pull/1779), the issue seems to have been resolved (along with the `temp` issue it was intended to address in the first place). Thank you @john-hen!

**Comment by koen-vg** [comment]
Even after the mentioned PR (https://github.com/snakemake/snakemake/pull/1779), I'm still having this issue actually. Can do some digging to see where this might originate.

**Comment by koen-vg** [comment]
After some anecdotal evidence, it seems like the above does actually fix this bug, at least for me. I re-ran the same workflow that I previous had problems with using the above fix, and the file modification times do seem to consistently check out now. Not 100% conclusive evidence between the original problem isn't deterministic (i.e. files might have correct modification time order by accident) but I'm 90% confident that the fix works.

**Comment by johanneskoester** [comment]
Ok, let's consider this to be fixed for now by PR #2073. Thanks a lot folks!
